// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnswB_BVtl59qiSflMTrFpGx7AXumX_Pw',
    appId: '1:605142006227:android:428263b233b295f8981726',
    messagingSenderId: '605142006227',
    projectId: 'spmarket-83b78',
    storageBucket: 'spmarket-83b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDygMwrGC2cudWWMWneLv7LD_NXiSNA-CM',
    appId: '1:605142006227:ios:40904cb7bb4f07c8981726',
    messagingSenderId: '605142006227',
    projectId: 'spmarket-83b78',
    storageBucket: 'spmarket-83b78.firebasestorage.app',
    androidClientId:
        '605142006227-9562gk74led37vkdu59n65dkc05g9u0g.apps.googleusercontent.com',
    iosClientId:
        '605142006227-se5rgst2fpa0riati0u922ugk41ooaha.apps.googleusercontent.com',
    iosBundleId: 'com.cartlabs.spmarket',
  );
}
